version: '3'

# image: public.ecr.aws/z2b1m8m3/compose-test
services:
         back-end:
                 #image: z2b1m8m3/compose-test
               container_name: back-end
               build: ./back-end
               #cbentleywatson/labeled
               image: "cbentleywatson/pal-back-end:latest"
               #image: "cbentleywatson/labeled-image-last-test-last:my-tag"
               ports:
                       - 5011:5011
         front-end:
                build: ./pal-clone
                image: "cbentleywatson/pal-front-end:latest"
                ports:
                        - 3000:80
