version: '3'

# image: public.ecr.aws/z2b1m8m3/compose-test
services:
         back-end:
                 #image: z2b1m8m3/compose-test
               build: ./Docker-AWS-Crash-Course
               container_name: the-back-end
               ports:
                       - 5005:5000
         front-end:
                build: ./pal-clone
                container_name: the-front-end
                ports:
                        - 3000:3000
