#https://github.com/harblaith7/Docker-AWS-Crash-Course.git# pull official base image
FROM node:18-alpine3.15 as build


# add `/app/node_modules/.bin` to $PATH
#ENV PATH /pal-clone/node_modules/.bin:$PATH

# install app dependencies
#COPY pal-clone/package.json ./
#COPY pal-clone/package-lock.json ./
#RUN npm install 

#RUN npm install react-scripts@3.4.1 -g 

# add app
WORKDIR /app
COPY package.json .

#COPY . ./

# set working directory
#WORKDIR /pal-clone
RUN npm install 
COPY . .
# start app
# The EXPOSE command links the port the PROGRAAM sees to the Port Chrome communicates with. The second number is the port to use with the browser, the first is what react uses 

RUN npm run build

# Serving React with NGINX
FROM nginx:stable-alpine
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=build /app/build . 
# Would need to ensure the path to the build files is the same..
ENTRYPOINT ["nginx", "-g", "daemon off;"]

#EXPOSE 80
#EXPOSE 3000:3000
EXPOSE  3000
#EXPOSE 80:3000
#EXPOSE 3000:3000




#CMD ["npm", "start"]
#CMD ["npm", "run", "" ]
#CMD ["server","-s build"] 
# didn't work..

#CMD ["ls", "pal-clone/node_modules"]
